#!/usr/bin/bash

bspwm_dir="$HOME/.config/bspwm"
rofi_command="rofi -dmenu -theme $bspwm_dir/scripts/RiceSelector.rasi -i -markup-rows -no-show-icons -width 1000 -lines 15 -yoffset 40"

awk '/^[a-z]/ && last {print "<small>",$0,"\t",last,"</small>"} {last=""} /^#/{last=$0}' ~/.config/bspwm/sxhkdrc | \
column -t -s $'\t' | rofi -dmenu -i -markup-rows -no-show-icons -width 1000 -lines 15 -yoffset 40


